[package]
name = "ringvec"
version = "0.1.0"
description = "A simple ring buffer implementation on top of Vec"
edition = "2018"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "my_benchmark"
harness = false
